/*
 * Copyright (c) 2020 Nordic Semiconductor ASA
 *
 * SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
 */
#ifndef ZBOSS_BUILD_INFO_H__
#define ZBOSS_BUILD_INFO_H__

/**
 * This is an autogenerated file.
 * Please use release scripts to update it's contents.
 *
 * Repositories:
 * platform_ncs       ce3904a1071650c4e87af48160d7febcbfd7e666 https://projecttools.nordicsemi.no/bitbucket/scm/zoi/platform_ncs.git
 * zboss-stack-src    5333d644e6cc24e3e85c8e94614dbc022a2f769f https://projecttools.nordicsemi.no/bitbucket/scm/zoi/zboss_r23
 * ncs-zigbee         b1866f3f25517fe2009d74ff2a08504021840458 https://github.com/edmont/ncs-zigbee
 * nrf                ec2082c34bcfad9e1ca91e72d6e29247274369f8 https://github.com/nrfconnect/sdk-nrf
 * zephyr             a2bce9d3decd691d4748c2b0f9069845e0c08431 https://github.com/nrfconnect/sdk-zephyr
 * wfa-qt-control-app 1f19f0b23e42205bab5f34ace335fffa5e7d32ff https://github.com/nrfconnect/sdk-wi-fiquicktrack-controlappc
 * mcuboot            d2b3671987d1ca54492afe560c2444c3a9dc3000 https://github.com/nrfconnect/sdk-mcuboot
 * qcbor              751d36583a9ce1a640900c57e13c9b6b8f3a2ba2 https://github.com/laurencelundblade/QCBOR
 * mbedtls            92d44566209a0d94a571cc7f71a4a7b9262f7602 https://github.com/nrfconnect/sdk-mbedtls
 * oberon-psa-crypto  3a9005029dae919e3f6d9d4182465a8e2572cf9f https://github.com/nrfconnect/sdk-oberon-psa-crypto
 * nrfxlib            45ab53a5b36e67c361af590bfbe02f6c508ff248 https://github.com/nrfconnect/sdk-nrfxlib
 * trusted-firmware-m e476105018a2bf2dd8f87bca30a8e766846b4048 https://github.com/nrfconnect/sdk-trusted-firmware-m
 * psa-arch-tests     ba0487c40eb2b57676676604b4c17526790dbc94 https://github.com/nrfconnect/sdk-psa-arch-tests
 * matter             106cf3d26c6b3354fc2006aa71684a9905d1af64 https://github.com/nrfconnect/sdk-connectedhomeip
 * cjson              c6af068b7f05207b28d68880740e4b9ec1e4b50a https://github.com/nrfconnect/sdk-cjson
 * azure-sdk-for-c    308c171cb4b5eed266649012a68406487ec81fb2 https://github.com/nrfconnect/azure-sdk-for-c
 * cirrus             1c837bcc27de9ccc06b020b9500e1547e559a1df https://github.com/nrfconnect/sdk-mcu-drivers
 * openthread         0fe68ff23527e8bb9a9821ca96a255fccfbb44a7 https://github.com/nrfconnect/sdk-openthread
 * nrf_wifi           d28d7e972a208f5007f745bd0a116d4cde3c4100 https://github.com/nrfconnect/nrf_wifi
 * cmock              f65066f15d8248e6dcb778efb8739904a4512087 https://github.com/ThrowTheSwitch/cmock
 * memfault-firmware-sdk 1c22975c2cd44671549ea5ab2517282559203af6 https://github.com/memfault/memfault-firmware-sdk
 * bsim               a88d3353451387ca490a6a7f7c478a90c4ee05b7 https://github.com/BabbleSim/bsim_west
 * coremark           d5fad6bd094899101a4e5fd53af7298160ced6ab https://github.com/eembc/coremark
 * canopennode        dec12fa3f0d790cafa8414a4c2930ea71ab72ffd https://github.com/zephyrproject-rtos/canopennode
 * chre               c4c2f49fdcaa2fed49eb1db027696a5734a010d2 https://github.com/zephyrproject-rtos/chre
 * cmsis              512cc7e895e8491696b61f7ba8066b4a182569b8 https://github.com/zephyrproject-rtos/cmsis
 * cmsis-dsp          97512610ec92058f0119450b9e743eeb7e95b5c8 https://github.com/zephyrproject-rtos/cmsis-dsp
 * cmsis-nn           d20117c9e88cf9018d6fa06744dddac700c3e3a1 https://github.com/zephyrproject-rtos/cmsis-nn
 * cmsis_6            30a859f44ef8ab4dc8f84b03ed586fd16ccf9d74 https://github.com/zephyrproject-rtos/CMSIS_6
 * dhara              6f163ca05e174b168b4d148160b50eeaeeb561fc https://github.com/zephyrproject-rtos/dhara
 * edtt               c282625e694f0b53ea53e13231ea6d2f49411768 https://github.com/zephyrproject-rtos/edtt
 * fatfs              f4ead3bf4a6dab3a07d7b5f5315795c073db568d https://github.com/zephyrproject-rtos/fatfs
 * hal_nordic         3c08112f3d92c81b98134479c01d3cfd40f54016 https://github.com/zephyrproject-rtos/hal_nordic
 * hal_st             7a792882847223c72944791e0c48eed6101e6569 https://github.com/zephyrproject-rtos/hal_st
 * hal_tdk            fa54cb65535b0ed69564423c9e0bf4e7ee47dcb1 https://github.com/zephyrproject-rtos/hal_tdk
 * hal_wurthelektronik 7c1297ea071d03289112eb24e789c89c7095c0a2 https://github.com/zephyrproject-rtos/hal_wurthelektronik
 * hostap             a50c3c2c78eb3ed9709803eb7479d3df33d7c1bb https://github.com/zephyrproject-rtos/hostap
 * liblc3             48bbd3eacd36e99a57317a0a4867002e0b09e183 https://github.com/zephyrproject-rtos/liblc3
 * libmetal           66e084293b2a7ced5a73fbd247deddba8915883a https://github.com/zephyrproject-rtos/libmetal
 * libsbc             8e1beda02acb8972e29e6edbb423f7cafe16e445 https://github.com/zephyrproject-rtos/libsbc
 * littlefs           8f5ca347843363882619d8f96c00d8dbd88a8e79 https://github.com/zephyrproject-rtos/littlefs
 * loramac-node       fb00b383072518c918e2258b0916c996f2d4eebe https://github.com/zephyrproject-rtos/loramac-node
 * lvgl               85aa60d18b3d5e5588d7b247abf90198f07c8a63 https://github.com/zephyrproject-rtos/lvgl
 * mipi-sys-t         5a9d6055b62edc54566d6d0034d9daec91749b98 https://github.com/zephyrproject-rtos/mipi-sys-t
 * mldsa-native       3fc19982839305d305071f0de0c540bc9c9bea8a https://github.com/zephyrproject-rtos/mldsa-native
 * nanopb             5499fd4c9a478f8139eeb07a82c3b4468d6067f7 https://github.com/zephyrproject-rtos/nanopb
 * net-tools          64d7acc661ae2772282570f21beab85d02f2f35c https://github.com/zephyrproject-rtos/net-tools
 * nrf_hw_models      158b9710d6e10c57b2c623f8f4178f0bbc85c23f https://github.com/zephyrproject-rtos/nrf_hw_models
 * open-amp           5efe7974f9546582e99f5a842a816ea4b65f5227 https://github.com/zephyrproject-rtos/open-amp
 * percepio           f9159fe3c79578e8d90c8593e83f9862d9b8962c https://github.com/zephyrproject-rtos/percepio
 * picolibc           01254932e8e81085817ed61fd858648584ffe37c https://github.com/zephyrproject-rtos/picolibc
 * segger             50892fdbcf2f570e67baa72b8894a66b16946f72 https://github.com/zephyrproject-rtos/segger
 * tf-m-tests         7bb7b7999ee74a0aebb9a91fd8056698c552008b https://github.com/zephyrproject-rtos/tf-m-tests
 * tf-psa-crypto      dc575a2ddcc8cb16275d24c42a52eaf79ebe2231 https://github.com/zephyrproject-rtos/tf-psa-crypto
 * uoscore-uedhoc     dc0ab6345450668de3f9597320a48c5a2d409bb6 https://github.com/zephyrproject-rtos/uoscore-uedhoc
 * zcbor              9164bd18dcd88ff9d9ef98279501fc1093571017 https://github.com/zephyrproject-rtos/zcbor
 */


/** ZBOSS build tag */
#define ZBOSS_BUILD_TAG "5333d644e"

/** ZBOSS platform build tag */
#define ZBOSS_PLATFORM_BUILD_TAG "v4.2.2.4+v6.0.7"

/** ZBOSS build date (UTC) */
#define ZBOSS_BUILD_DATE 20260619

/** ZBOSS build time (UTC) */
#define ZBOSS_BUILD_TIME 112452


#endif /* ZBOSS_BUILD_INFO_H__ */
