/*
 * Copyright (c) 2020 Nordic Semiconductor ASA
 *
 * SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
 */
#ifndef ZBOSS_BUILD_INFO_H__
#define ZBOSS_BUILD_INFO_H__

/**
 * This is an autogenerated file.
 * Please use release scripts to update it's contents.
 *
 * Repositories:
 * platform_ncs       947193f49608aab640f176ea411d8d6a7f318845 https://projecttools.nordicsemi.no/bitbucket/scm/zoi/platform_ncs.git
 * zboss-stack-src    5333d644e6cc24e3e85c8e94614dbc022a2f769f https://projecttools.nordicsemi.no/bitbucket/scm/zoi/zboss_r23
 * ncs-zigbee         72d9a0dba904391291534f0996f7e74d7018bb19 https://github.com/edmont/ncs-zigbee
 * nrf                ba167d9f3db4abbdc9b67887ca3ea66c64f2d956 https://github.com/nrfconnect/sdk-nrf
 * zephyr             fd9204a02d52630660ce8d729945a4dd743feabf https://github.com/nrfconnect/sdk-zephyr
 * wfa-qt-control-app 63b3fa8bab483d021dd8c09a581887b039aa9e8a https://github.com/nrfconnect/sdk-wi-fiquicktrack-controlappc
 * mcuboot            fce4dac2e6295cf98bd02a85f7c4254f6102106d https://github.com/nrfconnect/sdk-mcuboot
 * qcbor              751d36583a9ce1a640900c57e13c9b6b8f3a2ba2 https://github.com/laurencelundblade/QCBOR
 * mbedtls            5bb86aeae32420e4f537e5cc390f7219a1bcf500 https://github.com/nrfconnect/sdk-mbedtls
 * oberon-psa-crypto  fd1f2aa156d8beb78584dfbaf30df30bf8f6568f https://github.com/nrfconnect/sdk-oberon-psa-crypto
 * nrfxlib            cfb98f4bcd4efe00df0c741e137b42f307680402 https://github.com/nrfconnect/sdk-nrfxlib
 * trusted-firmware-m 4f72bf583e71503965aed78f819474f25ce45a81 https://github.com/nrfconnect/sdk-trusted-firmware-m
 * psa-arch-tests     ba0487c40eb2b57676676604b4c17526790dbc94 https://github.com/nrfconnect/sdk-psa-arch-tests
 * matter             47099d700f9b4713d914cfeee62680548ecde190 https://github.com/nrfconnect/sdk-connectedhomeip
 * cjson              c6af068b7f05207b28d68880740e4b9ec1e4b50a https://github.com/nrfconnect/sdk-cjson
 * azure-sdk-for-c    308c171cb4b5eed266649012a68406487ec81fb2 https://github.com/nrfconnect/azure-sdk-for-c
 * cirrus             1c837bcc27de9ccc06b020b9500e1547e559a1df https://github.com/nrfconnect/sdk-mcu-drivers
 * openthread         0e26667136c2c49d42c96b8104ec2e90e8d55e4d https://github.com/nrfconnect/sdk-openthread
 * cmock              f65066f15d8248e6dcb778efb8739904a4512087 https://github.com/ThrowTheSwitch/cmock
 * memfault-firmware-sdk 5ee5e5af88630da814fccdd126421f32280d6538 https://github.com/memfault/memfault-firmware-sdk
 * bsim               a88d3353451387ca490a6a7f7c478a90c4ee05b7 https://github.com/BabbleSim/bsim_west
 * coremark           d5fad6bd094899101a4e5fd53af7298160ced6ab https://github.com/eembc/coremark
 * hostap             957e9578648b7da0e35f20dbf9a0c35fce9dc4af https://github.com/nrfconnect/sdk-hostap
 * canopennode        dec12fa3f0d790cafa8414a4c2930ea71ab72ffd https://github.com/zephyrproject-rtos/canopennode
 * chre               3b32c76efee705af146124fb4190f71be5a4e36e https://github.com/zephyrproject-rtos/chre
 * cmsis              512cc7e895e8491696b61f7ba8066b4a182569b8 https://github.com/zephyrproject-rtos/cmsis
 * cmsis-dsp          97512610ec92058f0119450b9e743eeb7e95b5c8 https://github.com/zephyrproject-rtos/cmsis-dsp
 * cmsis-nn           e9328d612ea3ea7d0d210d3ac16ea8667c01abdd https://github.com/zephyrproject-rtos/cmsis-nn
 * cmsis_6            30a859f44ef8ab4dc8f84b03ed586fd16ccf9d74 https://github.com/zephyrproject-rtos/CMSIS_6
 * edtt               c282625e694f0b53ea53e13231ea6d2f49411768 https://github.com/zephyrproject-rtos/edtt
 * fatfs              f4ead3bf4a6dab3a07d7b5f5315795c073db568d https://github.com/zephyrproject-rtos/fatfs
 * hal_nordic         1acb428a205bad58f3dfd4e38f2d1663bb784ba1 https://github.com/zephyrproject-rtos/hal_nordic
 * hal_st             6d963459acecfd2f9748ab506385a3188d8768f0 https://github.com/zephyrproject-rtos/hal_st
 * hal_tdk            60708f2c7bf078bc9cc3a7737ef955ec572c23e2 https://github.com/zephyrproject-rtos/hal_tdk
 * hal_wurthelektronik 7c1297ea071d03289112eb24e789c89c7095c0a2 https://github.com/zephyrproject-rtos/hal_wurthelektronik
 * liblc3             48bbd3eacd36e99a57317a0a4867002e0b09e183 https://github.com/zephyrproject-rtos/liblc3
 * libmetal           66e084293b2a7ced5a73fbd247deddba8915883a https://github.com/zephyrproject-rtos/libmetal
 * libsbc             8e1beda02acb8972e29e6edbb423f7cafe16e445 https://github.com/zephyrproject-rtos/libsbc
 * littlefs           8f5ca347843363882619d8f96c00d8dbd88a8e79 https://github.com/zephyrproject-rtos/littlefs
 * loramac-node       fb00b383072518c918e2258b0916c996f2d4eebe https://github.com/zephyrproject-rtos/loramac-node
 * lvgl               94ae6c0535aa6ac4b08a75f4ae2c3a08cacb5c41 https://github.com/zephyrproject-rtos/lvgl
 * mipi-sys-t         5a9d6055b62edc54566d6d0034d9daec91749b98 https://github.com/zephyrproject-rtos/mipi-sys-t
 * nanopb             5499fd4c9a478f8139eeb07a82c3b4468d6067f7 https://github.com/zephyrproject-rtos/nanopb
 * net-tools          64d7acc661ae2772282570f21beab85d02f2f35c https://github.com/zephyrproject-rtos/net-tools
 * nrf_hw_models      63ccab2988bf4c144b3cd324a0277e03206fa413 https://github.com/zephyrproject-rtos/nrf_hw_models
 * nrf_wifi           1a4e59f4c6685877f6bff08bb1812bf9318da6d2 https://github.com/zephyrproject-rtos/nrf_wifi
 * open-amp           5efe7974f9546582e99f5a842a816ea4b65f5227 https://github.com/zephyrproject-rtos/open-amp
 * percepio           132ed87d617578a6cb70a2443f43e117c315e0f0 https://github.com/zephyrproject-rtos/percepio
 * picolibc           ca8b6ebba5226a75545e57a140443168a26ba664 https://github.com/zephyrproject-rtos/picolibc
 * segger             50892fdbcf2f570e67baa72b8894a66b16946f72 https://github.com/zephyrproject-rtos/segger
 * tf-m-tests         cde5b6ed540d3ff5a09564fded6b39b0a70ad3bf https://github.com/zephyrproject-rtos/tf-m-tests
 * uoscore-uedhoc     ac80c3bf2b88deec86d129654fbde09761582342 https://github.com/zephyrproject-rtos/uoscore-uedhoc
 * zcbor              9164bd18dcd88ff9d9ef98279501fc1093571017 https://github.com/zephyrproject-rtos/zcbor
 */


/** ZBOSS build tag */
#define ZBOSS_BUILD_TAG "5333d644e"

/** ZBOSS platform build tag */
#define ZBOSS_PLATFORM_BUILD_TAG "v4.2.2.4+v6.0.7"

/** ZBOSS build date (UTC) */
#define ZBOSS_BUILD_DATE 20260515

/** ZBOSS build time (UTC) */
#define ZBOSS_BUILD_TIME 105503


#endif /* ZBOSS_BUILD_INFO_H__ */
